services:
  db:
    image: postgres:13-alpine
    container_name: matchme-db
    environment:
      POSTGRES_USER: matchme
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: matchme
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matchme -d matchme"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: matchme-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=matchme
      - DB_PASSWORD=securepassword
      - DB_NAME=matchme
      - JWT_SECRET=your_jwt_secret_here
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: matchme-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: